---
- name: Install docker engine
  hosts: docker_hosts
  become: true
  gather_facts: true
  pre_tasks:
    - name: Check distro
      ansible.builtin.assert:
        that: 
          - "'{{ ansible_distribution }}' in docker_allowed_distribs"
        fail_msg: "Not allowed on {{ ansible_distribution }} {{ ansible_distribution_version }}"
        success_msg: "Installation allowed on {{ ansible_distribution }} {{ ansible_distribution_version }}"

  tasks:

    - include_role:
        name: docker
      